<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>VPet_Simulator.Core.MutiPlatform</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="LinePutScript" Version="1.11.9" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VPet_Simulator.Core.Base\VPet_Simulator.Core.Base.csproj" />
  </ItemGroup>
</Project>
