<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VPet-Simulator.Core\VPet-Simulator.Core.csproj" />
    <ProjectReference Include="..\VPet-Simulator.Windows.Interface\VPet-Simulator.Windows.Interface.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HanumanInstitute.MvvmDialogs" Version="2.4.0" />
    <PackageReference Include="HanumanInstitute.MvvmDialogs.Wpf" Version="2.4.0" />
    <PackageReference Include="LinePutScript" Version="1.11.9" />
    <PackageReference Include="LinePutScript.Localization.WPF" Version="1.0.7" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HKW.Mapper" Version="0.1.4" />
    <PackageReference Include="HKW.Utils" Version="1.4.0" />
    <PackageReference Include="HKW.WPF" Version="1.2.0" />
    <PackageReference Include="HKW.CommonValueConverters" Version="0.2.0" />
    <PackageReference Include="HKW.MVVM" Version="0.1.1" />
    <PackageReference Include="HKW.MVVM.SourceGenerator" Version="0.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
  <Target Name="DisableMvvmToolkitSourceGenerators" BeforeTargets="CoreCompile">
    <ItemGroup>
      <_MvvmToolkitAnalyzers
        Include="@(Analyzer)"
        Condition="$([System.String]::Copy('%(Analyzer.Filename)').Contains('CommunityToolkit.Mvvm.SourceGenerators'))"
      />

      <Analyzer Remove="@(_MvvmToolkitAnalyzers)" />
    </ItemGroup>
  </Target>
</Project>
